#修改当前程序的端口号
server:
  port: 8001
#加载MyBatis的配置文件和映射文件
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  #给实体类取个别名
  type-aliases-package: com.os.springcloud.entities
  #加载MyBatis的映射文件
  mapper-locations: mybatis/mapper/**/*.xml
#当前微服务取个别名
spring:
  application:
    name: dingguoshuaiAPP
  #配置连接数据库的信息
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dept_01
    username: root
    password: root

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
#      defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: DingGuoShuai8001  #给当前服务去取个别名
    prefer-ip-address: true #可以将微服务别名对应到具体的IP地址（便于后期维护）

info:
  app.name: SpringCloud_8001_provider
  company.name: com.provider.com
  build.artifactId: microservicecloud-provider_dept_8001
  build.version: 1.0-SNAPSHOT