server:
  port: 7003
eureka:
  instance:
    hostname: eureka7003:com
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/ #当前连接时Eureka官方指定写法，需要与官网保持一致
